[theme]
name = "Everblush"

[theme.base]
white = "#dadada"
black = "#0f1619"
grey = "#232a2d"
blue = "#67b0e8"
red = "#e57474"
yellow = "#e5c76b"
orange = "#fcb163"
green = "#8ccf7e"
purple = "#bab3e5"
cyan = "#6cbfbf"
magenta = "#c47fd5"

[theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#aeb4b3"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$blue"
number = "$yellow"
property = "$red"
"punctuation.delimiter" = "$yellow"
selfKeyword = "$purple"
string = "$green"
"string.escape" = "$cyan"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
variable = "$red"
"variable.other.member" = "$green"

[theme.ui]
"activity.background" = "#0f1619"
"activity.current" = "$black"
"completion.background" = "#1b2225"
"completion.current" = "#141b1e"
"editor.background" = "$black"
"editor.caret" = "#528BFF"
"editor.current_line" = "#141b1e"
"editor.dim" = "#5C6370"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.link" = "$blue"
"editor.selection" = "#2a3134"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#2C313C37"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#2C313C"
"error_lens.other.foreground" = "#5C637037"
"error_lens.warning.background" = "#2C313C"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#0f1619"
"inlay_hint.background" = "#2C313C"
"inlay_hint.foreground" = "$white"
"lapce.active_tab" = "#67b0e8"
"lapce.border" = "#000000"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.inactive_tab" = "#grey"
"lapce.scroll_bar" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#0f1619"
"palette.current" = "#1b2225"
"panel.background" = "#141b1e"
"panel.current" = "#0f1619"
"panel.hovered" = "#2a3134"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "#141b1e"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#0f1619"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#dadada"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
