[theme]
name = ""

[theme.base]
white = "#dadada"
black = "#141b1e"
grey = "#b3b9b8"
blue = "#67b0e8"
red = "#e57474"
yellow = "#e5c76b"
orange = "#fcb163"
green = "#8ccf7e"
purple = "#bab3e5"
cyan = "#6cbfbf"
magenta = "#c47fd5"

[theme.syntax]
attribute = "$yellow"
builtinType = "#94e2d5"
comment = "#aeb4b3"
constant = "$yellow"
constructor = "$yellow"
embedded = "#94e2d5"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "#94e2d5"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "#cba6f7"
"keyword.control" = "$purple"
method = "$blue"
number = "$yellow"
property = "$red"
selfKeyword = "#cba6f7"
string = "$green"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
type = "$yellow"
"type.builtin" = "#94e2d5"
typeAlias = "$yellow"
"variable.other.member" = "$red"

[theme.ui]
"activity.background" = "#1b2225"
"activity.current" = "#585b70"
"completion.background" = "#1b2225"
"completion.current" = "#141b1e"
"editor.background" = "#1e1e2e"
"editor.caret" = "#94e2d5"
"editor.current_line" = "#2C313C"
"editor.dim" = "#7f849c"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "#bac2de"
"editor.link" = "#f5e0dc"
"editor.selection" = "#585b70"
"error_lens.error.background" = "#2C313C37"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#2C313C"
"error_lens.other.foreground" = "#5C637037"
"error_lens.warning.background" = "#2C313C"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#0f1619"
"inlay_hint.background" = "#2C313C37"
"inlay_hint.foreground" = "#7f849c"
"lapce.active_tab" = "#67b0e8"
"lapce.border" = "#181825"
"lapce.dropdown_shadow" = "#181825"
"lapce.error" = "$red"
"lapce.inactive_tab" = "#1b2225"
"lapce.scroll_bar" = "#6c7086"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#a6adc8"
"palette.background" = "#2a3134"
"palette.current" = "#1b2225"
"panel.background" = "#1e1e2e"
"panel.current" = "#2a3134"
"panel.hovered" = "#2a3134"
"source_control.added" = "##a6d18932"
"source_control.modified" = "#8caaee32"
"source_control.removed" = "#ea999c32"
"status.background" = "#1e1e2e"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "#cba6f7"
"status.modal.visual" = "$yellow"
"terminal.background" = "#1e1e2e"
"terminal.black" = "#45475a"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#0f1619"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "#94e2d5"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "#f5c2e7"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#dadada"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "#f5e0dc"
"terminal.cyan" = "#94e2d5"
"terminal.foreground" = "#cdd6f4"
"terminal.green" = "$green"
"terminal.magenta" = "#f5c2e7"
"terminal.red" = "$red"
"terminal.white" = "#bac2de"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
